language: java
sudo: false

jdk:
#  - openjdk11
#  - oraclejdk11
  - openjdk8
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

install: true

script:
  - travis_wait 30 ./mvnw clean install -DskipTests=true -Dcheckstyle.skip=false -Drat.skip=false -Dmaven.javadoc.skip=true -q -e
  - travis_wait 30 ./mvnw cobertura:cobertura -DskipTests=true -Dmaven.javadoc.skip=true -q -e

after_success:
  - bash <(curl -s https://codecov.io/bash)
