language: java
sudo: false

jdk:
  - openjdk11
  - oraclejdk11
  - openjdk8
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

install: true

script:
  - travis_wait 30 mvn clean install -DskipTests=true -Dcheckstyle.skip=false -Drat.skip=false -Dmaven.javadoc.skip=true
  - mvn cobertura:cobertura
